### ISSUE TITLE
Add get chain id method as per EIP 695

### ISSUE THREAD

**Issue by BelfordZ** [etclabscore/ethereum-json-rpc-specification#86]
**Is your feature request related to a problem? Please describe.**
EIP-695 adds a new JSON rpc method. Sadly, they did not include an OpenRPC method definition in the EIP. [It is now being marked as final](https://github.com/ethereum/EIPs/pull/2432), but can still be improved with an OpenRPC method def.

**Describe the solution you'd like**
Write the method definition, and PR it back to the EIP, as well as this repo.

**Additional context**
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-695.md

**Comment by shanejonas** [comment]
This method is already defined here:

https://github.com/etclabscore/ethereum-json-rpc-specification/blob/5cf0b4fbae8f760923bc3fa6a6fc776775334093/openrpc.json#L148-L162

could PR that definition to EIP-695?

**Comment by BelfordZ** [comment]
oh yea! nice
